version: '3.8'

services:
  urbackup-server:
    image: uroni/urbackup-server:latest
    container_name: urbackup-server
    environment:
      PUID: 0
      PGID: 0
      TZ: 'Europe/Lisbon'
    ports:
      - '55414:55414' 
    volumes:
      - /srv/docker/urbackup-server:/var/urbackup
      - /srv/docker/urbackup-server/backups:/backups
      # Uncomment the next line if you want to bind-mount the www-folder
      #- /path/to/wwwfolder:/usr/share/urbackup
    #network_mode: "host"
    # Uncomment the following two lines if you're using BTRFS support
    #cap_add:
    #  - SYS_ADMIN
    # Uncomment the following two lines if you're using ZFS support
    #devices:
    #  - /dev/zfs:/dev/zfs
    networks:
      - coiso
    restart: unless-stopped


  urbackup-client:
    image: uroni/urbackup-client:latest
    container_name: urbackup-client
    environment:
      TZ: 'Europe/Lisbon'
      URBACKUP_SERVER_NAME: example.com
      URBACKUP_CLIENT_NAME: exampleclientname
      URBACKUP_CLIENT_AUTHKEY: secretkey
    volumes:
      - /srv/docker/urbackup-server/backups:/backup  
    networks:
      - coiso
    restart: unless-stopped

networks:
  coiso:
    name: coiso
    external: true    