version: '3.8'

services:
  hermes:
    image: nousresearch/hermes-agent:latest
    container_name: hermes
    restart: unless-stopped
    #user: "1000:1000"
    env_file:
      - /srv/docker/env/hermes.env
    volumes:
      - /srv/docker/hermes:/opt/data
      - "/srv/docker/obsidian/Obsidian Vault:/vault"
    command: gateway run
    networks:
      - coiso
      - development-server

networks:
  coiso:
    name: coiso
    external: true
  development-server:
    name: development-server
    external: true