services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.kerumirembora.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.kerumirembora.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        puma['worker_processes'] = 0
        sidekiq['concurrency'] = 7
        alertmanager['enable'] = false
        gitlab_exporter['enable'] = false
        gitlab_kas['enable'] = false
        node_exporter['enable'] = false
        postgres_exporter['enable'] = false
        prometheus_monitoring['enable'] = false
        prometheus['enable'] = false
        puma['exporter_enabled'] = false
        redis_exporter['enable'] = false
        sidekiq['metrics_enabled'] = false
        gitaly['configuration'] = {
            concurrency: [
              {
                'rpc' => "/gitaly.SmartHTTPService/PostReceivePack",
                'max_per_repo' => 3,
              }, {
                'rpc' => "/gitaly.SSHService/SSHUploadPack",
                'max_per_repo' => 3,
              },
            ],
            cgroups: {
              count: 0,
              mountpoint: '',
              hierarchy_root: '',
            }
        }
        gitaly['env'] = {
          'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2'
        }
        gitlab_rails['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
        }
        gitaly['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
        }
    ports:
      - '8011:80'
      - '4431:443'
      - '2222:22'
    volumes:
      - /srv/docker/gitlab/config:/etc/gitlab
      - /srv/docker/gitlab/logs:/var/log/gitlab
      - /srv/docker/gitlab/data:/var/opt/gitlab
    networks:
      - coiso
      - development-server

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /srv/docker/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  networks:
      - coiso      
      - development-server
      
networks:
  coiso:
    name: coiso
    external: true
  development-server:
    name: development-server
    external: true