services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.kerumirembora.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.kerumirembora.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports:
      - '8011:80'
      - '4431:443'
      - '2222:22'
    volumes:
      - /srv/docker/gitlab/config:/etc/gitlab
      - /srv/docker/gitlab/logs:/var/log/gitlab
      - /srv/docker/gitlab/data:/var/opt/gitlab
    networks:
      - coiso

networks:
  coiso:
    name: coiso
    external: true