services:
  openclaw-gateway:
    container_name: openclaw-gateway
    # image: local/openclaw:2026.2.26 # built from @coiso /srv/docker/_src/openclaw/Dockerfile.dev
    # pull_policy: never
    image: gitlabcr.kerumirembora.com/xungamancorp/openclaw:2026.3.11
    user: "1000:1000"
    env_file:
      - /srv/docker/env/openclaw.env   
    volumes:
      - /srv/docker/openclaw/config:/home/node/.openclaw
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "lan",
        "--port",
        "18789",
      ]
    networks:
      - coiso

networks:
  coiso:
    name: coiso
    external: true