version: "3.8"

services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /srv/docker/dashy/app/user-data/conf.yml:/app/user-data/conf.yml
    ports:
      - 3010:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - coiso
      
networks:
  coiso:
    name: coiso
    external: true