services:
  maestro-api:
    image: gitlabcr.kerumirembora.com/xungamancorp/maestro/api:qa-latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__WeatherDb: ${ConnectionStrings__WeatherDb}
    networks:
      - coiso
      - development-server

  maestro-webapp:
    image: gitlabcr.kerumirembora.com/xungamancorp/maestro/webapp:qa-latest
    restart: unless-stopped
    environment:
      API_BASEPATHURL: https://maestro-api-qa.kerumirembora.com
    networks:
      - coiso
      - development-server

networks:
  coiso:
    external: true
  development-server:
    external: true
