services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID: 1000
      - PGID: 1000
      - TZ: 'Europe/Lisbon'
      #- CLI_ARGS= #optional
    volumes:
      - /srv/docker/duplicati/appdata/config:/config
      - /srv/docker/duplicati/backups:/backups
      - /srv/docker/duplicati/source:/source
    ports:
      - 8200:8200
    networks:
      - coiso
    restart: unless-stopped

networks:
  coiso:
    name: coiso
    external: true